name: 'Build Docker image'
description: 'Build a Docker image from a tagged release'
author: 'Flownative'
inputs:
  tag_ref:
    description: 'The full tag reference. This must be a semver tag ref of an existing tagged image. For example, `refs/tags/v1.2.5-12`'
    required: true
    default: ''
  git_sha:
    description: 'The SHA hash of the Git commit being used for the build. If set, this value is used as a label for the resulting Docker image'
    required: false
    default: ''
  git_repository_url:
    description: 'The URL leading to the Git repository. If set, this value is used as a label for the resulting Docker image'
    required: false
    default: ''
  image_name:
    description: 'The image name to build, without tag. For example, `flownative/docker-magic-image/magic-image`'
    required: true
    default: ''
  registry_password:
    description: 'Password / token for the Github Docker image registry'
    required: true
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'package'
  color: 'blue'
